### ISSUE TITLE
ID Value size

### ISSUE THREAD

**Issue by slothbag** [lexansoft/etherid.org#1]
Hi, was playing around with this, looks like my id value got truncated to 32 bytes.. 

Is there any chance of allowing larger strings?

**Comment by lexansoft** [comment]
No. On the info page you can see: "The domain name is in fact a binary 32 byte value." This is the "ethereum virtual machine word".

**Comment by slothbag** [comment]
I added a domain name, that was under 32 bytes so thats ok. then I added a new "ID", with a short key.. but the value part I needed it to be longer.. any reason to keep the "Value" field at 32 bytes?

**Comment by lexansoft** [comment]
Once again. The 32 bytes is the Ethereum VM word. If you want longer value, you will need to keep it in several IDs.

**Comment by slothbag** [comment]
Could the value not be of a "string" type?  They are dynamically sized byte arrays.  Might be slightly more expensive but allows greater flexibility.

**Comment by lexansoft** [comment]
The values are not strings. They are always numbers. You can interpret a
number as a UTF string.

Yes, you are right, it was a possibility to store values as actual strings.
I decided to make it as simple as possible. (but useful ;) For most cases
32 bytes are enough, and you can retrieve the value in one read operation.
And from another side, if you want to store some numeric parameter, it will
be stored the most effective and compact way.

Alexandre Naverniouk

**Comment by slothbag** [comment]
Great, thanks for your help :)

**Comment by slothbag** [comment]
FYI, I wrote this simple app to resolve domain names (using etherid.org) for use in the Hyperboria/CJDNS meshnet.

https://github.com/slothbag/EthHypeDns

**Comment by lexansoft** [comment]
Great. Good job!

Alexandre Naverniouk
