### ISSUE TITLE
http://etherid.org/#tabs-all status?

### ISSUE THREAD

**Issue by ghost** [lexansoft/etherid.org#15]
Hi. This looks very interesting. Is this service actually up and running? and how do I make use of it? For example, searching for ids does not return any values.

http://etherid.org/#tabs-all

**Comment by lexansoft** [comment]
It is up and running. You probably have the checkbox "Only My Domains" on. So the search only shows your domains. And you do not have one. 

Search through all the domains is a long operation.  If you specify some specific domain on the "Register/Manage" page, you will get the result instantly.
