### ISSUE TITLE
Make Separate contract for logic and database

### ISSUE THREAD

**Issue by D-Nice** [lexansoft/etherid.org#16]
This should fix the immutability problem you had in the previous release due to a bug. Now the onus is on someone to transfer all the old data from the former contract into the new one. 

Instead, you can keep an immutable database contract, and a logic contract, which can be updated and does all the major operations. In between these two contracts, you'll have a resolver contract, which refers one to the other, and whitelists calls between them.

**Comment by lexansoft** [comment]
Yes, true, but in that case who will control the whitelist of contracts? I
do not want the owner to have any special rights? Who can trust EtherID if
I can switch the contract anytime to some different business logic?

Alexandre Naverniouk

**Comment by D-Nice** [comment]
Well, the last update can be interpreted as a contract switch to different business logic also. There will always have to be a degree of trust between the creator/owner and clients of the contract. I'm simply suggesting a more efficient way of upgrading contracts, rather than requiring transfers between contract databases due to errors in the logic.

You can add a condition that freezes updates for a set period of time or permanently if you believe you've come up with a bug-free contract that will never need any updates to its logic so there's no surprise changes. Yet, at the same time, any logic changes will be visible to any users, as it all operates on a blockchain.

You can also add a sanity check to the database contract itself to ensure the updated business logic adheres to whichever standards are required. I just find replacing a whole contract to be a bit archaic when we in fact can make them versionable.

**Comment by D-Nice** [comment]
This is a good Dapp, I'm just trying to give you some advice to avoid the following issues in the future:

> The transferring of the data was quite costly ;( The one contract call costs about 0.003 ETH, but when you multiply it by 32K you get about 100 ETH. ;(

**Comment by lexansoft** [comment]
Yes. I see your point. Changing the contract is changing the business
logic.

At least it is done openly and not behind the scene. And there is no way I
can switch the logic for 10 min, process malicious transaction and then
switch it back.

We are all learning here ;)

But I do agree, it should be some better way. Not that costly ;)

Thank you.

Alexandre Naverniouk

**Comment by D-Nice** [comment]
I agree we are all learning here :).

I understand your hesitance when it comes to the change, but with the aforementioned sanity checks, you can ensure no malicious transactions go through. 

Libraries are another option, I haven't explored yet fully though.

Best of luck.
