### ISSUE TITLE
Cancle button does not work

### ISSUE THREAD

**Issue by 5chdn** [lexansoft/etherid.org#2]
I accidently tried to load all available domains and it went through a huge list of entries.

Clicking cancle did not stop that process. (On all domains tab.)

**Comment by lexansoft** [comment]
The list generation works in chunks. After you click cancel the program still finishes the current chunk (about 100 domains) and then terminates. On a slow computer it might take some time.

**Comment by 5chdn** [comment]
Ah okay. Thanks.
