### ISSUE TITLE
Add ID doesn't seem to do anything, even though the domain has been purchased and claimed

### ISSUE THREAD

**Issue by D4ndellion** [lexansoft/etherid.org#5]
This happens in both bulk, and the manual one.

**Comment by lexansoft** [comment]
It takes some tome for the network to process the transaction. Please give it 5 min to be updated.

**Comment by D4ndellion** [comment]
It's been two days

**Comment by lexansoft** [comment]
what domain, what id?

Alexandre Naverniouk

**Comment by D4ndellion** [comment]
Dandellion, first ID im trying to add. the name should be "ip"

**Comment by lexansoft** [comment]
Hmm... I just claimed a domain "teaparty" and added ID "ip" no problem.

Do you use mist? Or unlocked geth?

Alexandre Naverniouk

**Comment by D4ndellion** [comment]
unlocked geth

**Comment by D4ndellion** [comment]
I can try using mist though

**Comment by D4ndellion** [comment]
interesting difference between mist and browser
![2016-02-10_21-50-33](https://cloud.githubusercontent.com/assets/990767/12961370/6be99216-d040-11e5-86b0-c921e7713890.png)
tried sending the transaction through mist now

**Comment by D4ndellion** [comment]
Still nothing

**Comment by D4ndellion** [comment]
The data in the transaction is

`0xeb1ff8450000000000000000000000000000000000000000000044616e64656c6c696f6e000000000000000000000000000000000000000000000000000000000000697000000000000000000000000000000000000035312e3137342e3138352e313938`

**Comment by lexansoft** [comment]
Hmm looks good.

Do you have enough ETH on your account for the fee?

Alexandre Naverniouk

**Comment by D4ndellion** [comment]
yeah, 1,856.39 finney should be enough for the gas and fee

**Comment by lexansoft** [comment]
Very strange. Put 1ETH price on the domain. I will buy it from you to play
with.

Alexandre Naverniouk

**Comment by lexansoft** [comment]
Wait, I see a problem. The mist version does not show the proper domain.
Give me a second.

Alexandre Naverniouk

**Comment by D4ndellion** [comment]
the domain thing happens with all domains
![mist_2016-02-10_23-18-50](https://cloud.githubusercontent.com/assets/990767/12963806/090a7aa4-d04d-11e5-902f-8125da4b357e.png)
note that the id is still attatched

**Comment by D4ndellion** [comment]
also setting thr price on "Dandellion" _did_ work

**Comment by lexansoft** [comment]
It was some uglification problem. As you see on your picture Domain Name is
not shown correctly.

Please try now.

Please note, there is a bug in mist with cache. It keeps using the old
version even after refresh.

Alexandre Naverniouk

**Comment by D4ndellion** [comment]
does the cache bug happen even if i disable caching the in mistUI debug tool? Cause the domain is still showing up as the weird number

**Comment by D4ndellion** [comment]
opening the debug tool for the etherid tab itself did disable cache, domain name shows up correctly now.

**Comment by lexansoft** [comment]
I see our ip

Alexandre Naverniouk

**Comment by D4ndellion** [comment]
hheeeey that fixed it! thanks a lot for your help :smile:
