### ISSUE TITLE
'Address to use' is empty in Mist

### ISSUE THREAD

**Issue by RevCBH** [lexansoft/etherid.org#6]
Using Mist 0.3.6 on OS X 10.10.2

I've shared two identities w/ etherid.org, but when I go to claim a name, none are available.

**Comment by RevCBH** [comment]
Adding etherid.org to the list of dapps on the left and then re-adding an identity worked

**Comment by lexansoft** [comment]
Mist is not yet released. The available version is quite old. Once the program released officially, I will take a look.
